management.endpoints.web.exposure.include: "*"

hazelcast.max.no.heartbeat.seconds: 6

admin-application.url: http://localhost:8080/admin/companies/

news-application.url: http://localhost:8080/news/twitter/
